<!-- Start About -->
<a name="about" id="about"></a>
<section>
    <div class="about-us container">
        <img src="/img/logo-about-color.gif">
        <h2>We are <strong>Cascadeo</strong>: committed to taking care of our cloud deployments</h2>
        <h3>so you can focus on building your products and services.</h3>
    </div>

    <a name="news" id="news"></a>
    <div class="news container">
        <h3>Recently in the news</h3>
        <article>
            <h4>AMAZON WEB SERVICES - Michale Norring, Cascadeo CEO on Amazon Web Services Partnership</h4>
            <i>July 9, 2015</i>
            <p>Cascadeo CEO, Michael Norring, discusses how Cascadeo customers benefit from AWS, in a video launched at the AWS Summit held in New York.</p>
            <a href="#">Watch the interview</a>
        </article>
        <article>
            <h4>CHEF BLOG - Cascadeo recognized as certified Chef partner</h4>
            <i>April 15, 2015</i>
            <p>Cascadeo Corporation announced today that it is among the first members of the Chef Certified Partner Program.</p>
            <a href="#">Read the article</a>
        </article>
    </div>
</section>
<!-- End About -->

<!-- Start Services -->
<a name="services" id="services"></a>
<section class="services">
    <div class="center"><img src="/img/arrow-down-white.png"></div>
    <div class="container">
        <h1>Services</h1>
        <div>
            <img class="cloud-fix" src="/img/svg/icon-cloud.svg">
            <h4>The Cloud</h4>
            <p>Curabitur blandit tempus. Sed a posuere consectetur est at lobortis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante venenatis daphibus posuere velit aliquet. Nullam</p>
        </div>
        <div>
            <img src="/img/svg/icon-continuous.svg">
            <h4 style="margin-bottom: 40px;">Continuous Integration, Deployment, Automation</h4>
            <p>Curabitur blandit tempus. Sed a posuere consectetur est at lobortis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante venenatis daphibus posuere velit aliquet. Nullam</p>
        </div>
        <div style="margin-right: 0;">
            <img src="/img/svg/icon-247.svg">
            <h4>Managed Services</h4>
            <p>Curabitur blandit tempus. Sed a posuere consectetur est at lobortis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante venenatis daphibus posuere velit aliquet. Nullam</p>
        </div>
    </div>
    <div class="clearfix"></div>
</section>
<!-- End Services -->

<!-- Start help -->
<section class="help">
    <div class="container">
        <h3>One cloud does not fit all. Whether public, private, or a hybrid, we work closely with you to find the best solution that fits your objectives.</h3>
        <h4>Cascadeo will help with:</h4>
        <ul>
            <li><img src="/img/svg/icon-deploy.svg">Deploying a new service or product to the cloud</li>
            <li><img src="/img/svg/icon-migrating.svg">Migrating an existing service or product to the cloud</li>
            <li><img src="/img/svg/icon-optimizing.svg">Optimizing an existing cloud implementation</li>
            <li><img src="/img/svg/icon-migration.svg">Cloud to Cloud Migration</li>
            <li><img src="/img/svg/icon-managing.svg">Managing your cloud deployment</li>
        </ul>
        <aside>
            <img src="/img/svg/icon-24x7.svg">
            <h1>24/7</h1>
            <h2>Managed Services</h2>
            <p>We provide 24/7 managed support to keep your cloud infrastructure running</p>
        </aside>
        <div class="clearfix center">
            <a class="button" href="#contact">Contact Us For More Info</a>
        </div>
    </div>
</section>

<!-- Our Approach -->
<a name="our-approach" id="our-approach"></a>
<section class="our-approach">
    <div class="center"><img src="/img/arrow-down-white.png"></div>
    <div class="container">
        <h1>Our Approach</h1>
        <div class="approach-left"><img src="/img/pager-left-approach.png"></div>
        <ol>
            <li class="active" id="advise"><img src="/img/svg/icon-advise.svg"><span>1.</span> Advise</li>
            <li id="design"><img src="/img/svg/icon-design.svg"><span>2.</span> Design</li>
            <li id="build"><img src="/img/svg/icon-build.svg"><span>3.</span> Build it</li>
            <li id="automate"><img src="/img/svg/icon-automate.svg"><span>4.</span> Automate</li>
            <li id="maintain"><img src="/img/svg/icon-maintain.svg"><span>5.</span> Maintain</li>
        </ol>
        <aside>
            <div class="advise active">
                <h4>You are not just designing a cloud infrastructure, you are designing an operational environment</h4>
                <p>
                    Unlike traditional environments application code is constantly going to be changing.
                    Your environment not only has to be reliable and scalable, but it also has to be built as a dynamic operational infrastructure.
                </p>
                <p>
                    Cascadeo engineers know from experience that your developers will need to rapidly deploy code to keep up with the evolving demands of your customers.
                    We design solutions that pull together the right tools, process and infrastructure that allow you to focus on continuously imprving your product.
                    Marecenas faucibus mollis interdum.
                </p>
            </div>
            <div class="design" style="display: none;">
                <h4>2You are not just designing a cloud infrastructure, you are designing an operational environment</h4>
                <p>
                    Unlike traditional environments application code is cosntantly going to be changing.
                    Your environment not only has to be reliable and scalable, but it also has to be built as a dynamic operational infrastructure.
                </p>
                <p>
                    Cascadeo engineers know from experience that your developers will need to rapidly deploy code to keep up with the evolving demands of your customers.
                    We design solutions that pull together the right tools, process and infrastructure that allow you to focus on continuously imprving your product.
                    Marecenas faucibus mollis interdum.
                </p>
            </div>
            <div class="build" style="display: none">
                <h4>Test Content</h4>
                <p>Test Paragraph</p>
            </div>
            <div class="automate" style="display: none">
                <h4>Test Content</h4>
                <p>Test Paragraph</p>
            </div>
            <div class="maintain" style="display: none">
                <h4>Test Content</h4>
                <p>Test Paragraph</p>
            </div>
        </aside>
        <div class="approach-right"><img src="/img/pager-right-approach.gif"></div>
    </div>
    <div class="clearfix"></div>
</section>
<!-- End Our Approach -->

<!-- Start Future Needs -->
<section class="future-needs">
    <div class="container">
        <h3>We always work with the current and future needs of your business, including:</h3>
        <div style="margin-left: 0">
            <img src="/img/svg/icon-scalability.svg"><h3>Scalability</h3>
            <p>Curabitur blandit tempus. Sed a posuere consectetur est at lobortis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante venanatis dapibus</p>
        </div>
        <div>
            <img class="blue-svg" src="/img/svg/icon-durability.svg"><h3>Durability</h3>
            <p>Curabitur blandit tempus. Sed a posuere consectetur est at lobortis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante venanatis dapibus</p>
        </div>
        <div>
            <img src="/img/svg/icon-security.svg"><h3>Security & Compliance</h3>
            <p>Curabitur blandit tempus. Sed a posuere consectetur est at lobortis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante venanatis dapibus</p>
        </div>
    </div>
    <div class="clearfix"></div>
</section>
<!-- End Future Needs -->

<!-- Start Come Work For Us -->
<a name="careers" id="careers"></a>
<section class="work-for-us">
    <div class="banner"><h1 class="container">Come work for us</h1></div>
    <div class="container">
        <img src="/img/arrow-down-darkteal.gif">
        <h3>Got a passion for server automation? Love the idea of an organically grown, rapidly expanding company? <span>Join our team!</span></h3>
        <aside>
            <div class="testimonial-left"><img src="/img/pager-left-testimonial.gif"></div>
            <div class="testimonials">
                <div class="active">
                    <img src="/img/headshot-employee-sandi.jpg">
                    <p>
                        "It was great fun having the opportunity to certify as a Chef trainer. I'm able to bring my experience with Chef to Cascadeo clients with engineering projects as well as teach classes on behalf of Chef. Because I'm exposed to such a wide variety of projects, I'm learning more and faster at Cascadeo than I have at any other point in my career."

                    </p>
                    <span> - Sandi, Senior DevOps Engineer</span>
                </div>
                <div style="display: none;">
                    <img src="">
                    <p>
                        "2I love my job here. I feel constantly challenged in a non stressful way; I haven't reached any sort of ceiling. Further, faster, more enjoyable than a corporate giant."
                        <span> - Bort Berkshire, employee since 2011</span>
                    </p>
                </div>
                <div style="display: none;">
                    <img src="">
                    <p>
                        "3I love my job here. I feel constantly challenged in a non stressful way; I haven't reached any sort of ceiling. Further, faster, more enjoyable than a corporate giant."
                        <span> - Bort Berkshire, employee since 2011</span>
                    </p>
                </div>
                <div style="display: none;">
                    <img src="">
                    <p>
                        "4I love my job here. I feel constantly challenged in a non stressful way; I haven't reached any sort of ceiling. Further, faster, more enjoyable than a corporate giant."
                        <span> - Bort Berkshire, employee since 2011</span>
                    </p>
                </div>
            </div>
            <div class="testimonial-right"><img src="/img/pager-right-testimonial.gif"></div>
            <div class="clearfix center">
                <a class="button" href="#contact">Contact us about available careers</a>
            </div>
        </aside>
    </div>
</section>
<!-- End Come work for us -->

<!-- Start Partners -->
<section class="partners">
    <div class="container">
        <div>
            <img src="/img/partner-aws-color.gif">
            <p>aasdf asdf asdf aasdf asdf asdf aasdf asdf asdf aasdf asdf asdf aasdf asdf asdf aasdf asdf asdf aasdf asdf asdf </p>
        </div>
        <div>
            <img src="/img/partner-chef-color.gif">
            <p>aasdf asdf asdf aasdf asdf asdf aasdf asdf asdf aasdf asdf asdf aasdf asdf asdf aasdf asdf asdf aasdf asdf asdf </p>
        </div>
        <div>
            <img src="/img/partner-google-color.gif">
            <p>aasdf asdf asdf aasdf asdf asdf aasdf asdf asdf aasdf asdf asdf aasdf asdf asdf aasdf asdf asdf aasdf asdf asdf </p>
        </div>
        <div>
            <img src="/img/partner-equinox-color.gif">
            <p>aasdf asdf asdf aasdf asdf asdf aasdf asdf asdf aasdf asdf asdf aasdf asdf asdf aasdf asdf asdf aasdf asdf asdf </p>
        </div>
        <div>
            <img src="/img/partner-kubernetes-color.gif">
            <p>aasdf asdf asdf aasdf asdf asdf aasdf asdf asdf aasdf asdf asdf aasdf asdf asdf aasdf asdf asdf aasdf asdf asdf </p>
        </div>
        <div>
            <img src="/img/partner-microsoft-color.gif">
            <p>aasdf asdf asdf aasdf asdf asdf aasdf asdf asdf aasdf asdf asdf aasdf asdf asdf aasdf asdf asdf aasdf asdf asdf </p>
        </div>
        <aside class="clearfix">
            <h4>Interested in partnering with Cascadeo?</h4>
            <div class="center">
                <a class="button" href="#contact">Get in touch to partner</a>
            </div>
        </aside>
    </div>
</section>
<!-- End Partners -->

<!-- Start Contact form -->
<a name="contact" id="contact"></a>
<section class="contact-us">
    <div class="banner-contact"><h1 class="container">Contact Us</h1></div>
    <div class="center"><img src="/img/arrow-down-lightblue.gif"></div>
    <div class="container">
        <div>
            <h3>Questions? Comments? Want a Job?</h3>
            <img src="/img/google-map.jpg" style="margin-bottom: 20px;">
            <p>Cascadeo is located in the historic Rainer Brewery Building</p>
            <div>
                <p>Corporate HeadQuarters</p>
                <span>866-963-8677</span>
            </div>
            <div>
                <p>918 South Horton Street</p>
                <p>Suite 906</p>
                <p>Seattle, WA 98134</p>
            </div>
        </div>
        <div id="errors"></div>
        <form action="/forms/index/mail" method="post" id="contact-form">
            <input class="small-input" type="text" name="name" placeholder="Name">
            <input class="small-input" type="text" name="email" placeholder="Email">
            <input type="text" name="subject" placeholder="Subject">
            <textarea name="message" placeholder="Message..."></textarea>
            <button>Send Message</button>
        </form>

    </div>
    <div class="clearfix"></div>
</section>
<!-- End Contact Form -->
